language:
  python

cache: pip

python:
  - "3.6"

before_script:
  - pip install flake8

script:
  - flake8 benchmarks
  - python3 -m benchmarks.tests

before_deploy:
  - mkdir html && python3 -m benchmarks --display_format=html $EMAILS_ZIP_URL > html/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: html
  on:
    branch: master
